server: 
  port: 38084

spring:
  application:
    name: demo-server1
    description: demo-server1 开发服务环境的测试
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/prison_user?useUnicode=true&useSSL=false&characterEncoding=utf8&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
      shutdown-timeout: 100ms

eureka:
  client:
    registry-fetch-interval-seconds: 5 # 定时刷新本地缓存时间
    service-url:
      defaultZone: http://localhost:38080/eureka/

#eureka:
#  instance:
#    prefer-ip-address: true
#    # hostname: eureka.test.com
#    port: 38080
##    instance-id: ${spring.cloud.client.ip-address}:${server.http.port}
#    secure-port-enabled: true
#    non-secure-port-enabled: false
#
##    home-page-url: http://${spring.cloud.client.ip-address}:${server.http.port}/
##    status-page-url-path: http://${spring.cloud.client.ip-address}:${server.http.port}/actuator/info
##    health-check-url: http://${spring.cloud.client.ip-address}:${server.http.port}/health
#
#    lease-renewal-interval-in-seconds: 5  # 心跳间隔，5秒
#    lease-expiration-duration-in-seconds: 10 # 没有心跳的淘汰时间，10秒
#  client:
#    registry-fetch-interval-seconds: 5 # 定时刷新本地缓存时间
#    service-url:
#      defaultZone: http://${spring.cloud.client.ip-address}:${eureka.instance.port}/eureka/
